crypto_dict = {
    "ACH": "Alchemy Pay",
    "ADA": "Cardano",
    "ALGO": "Algorand",
    "APE": "ApeCoin",
    "APT": "Aptos",
    "ARB": "Arbitrum",
    "ASTR": "Astar",
    "ATOM": "Cosmos",
    "AVAX": "Avalanche",
    "BCH": "Bitcoin Cash",
    "BNB": "Binance Coin",
    "BONK": "Bonk",
    "BTC": "Bitcoin",
    "CAKE": "PancakeSwap",
    "DAI": "Dai",
    "DEXE": "DeXe",
    "DOGE": "Dogecoin",
    "DOT": "Polkadot",
    "ENA": "Ethena",
    "EOS": "EOS",
    "ETC": "Ethereum Classic",
    "ETH": "Ethereum",
    "FARTCOIN": "Fart Coin",
    "FET": "Fetch.ai",
    "FIL": "Filecoin",
    "HBAR": "Hedera",
    "HYPE": "Hyperliquid",
    "IOTA": "IOTA",
    "JASMY": "JasmyCoin",
    "JUP": "Jupiter",
    "KAS": "Kaspa",
    "LAYER": "LayerZero",
    "LEO": "UNUS SED LEO",
    "LINK": "Chainlink",
    "MOVE": "MoveCoin",
    "NEAR": "NEAR Protocol",
    "OP": "Optimism",
    "PEPE": "Pepe",
    "POPCAT": "Popcat",
    "PYTH": "Pyth Network",
    "SAND": "The Sandbox",
    "SHIB": "Shiba Inu",
    "SOL": "Solana",
    "STRK": "Starknet",
    "SUI": "Sui",
    "THETA": "Theta Network",
    "TON": "Toncoin",
    "TRUMP": "Trump Token",
    "TRX": "TRON",
    "TWT": "Trust Wallet Token",
    "USDC": "USD Coin",
    "USDT": "Tether",
    "VET": "VeChain",
    "VIRTUAL": "Virtual Coin",
    "WIF": "Dogwifhat",
    "WLD": "Worldcoin",
    "XLM": "Stellar Lumens",
    "XRM": "Monero",
    "XRP": "Ripple",
    "ZK": "ZKsync",
    "LTC": "Litecoin",
    "TFNY": "TFNY",
    "MNT": "Mantle",
    "OM": "MANTRA",
    "NOT": "Notcoin",
    "DOGS": "DOGS",
}